api:
 id: "16635465"
https:
 frequency : "10000"
 retry : "3"
 timeout : "60000"
 tls:
   keystore:
    keyStorePassword: "wincanton"
    privateKeyPassword: "wincanton"
    filePath: "certificates/server-keystore.jks"
   truststore:
    keyStorePassword: "wincanton"
    privateKeyPassword: "wincanton"
    filePath: "certificates/server-truststore.jks"

experience:
  c100: "sg"
  c101: "bnq"