#%RAML 1.0
title: int-p-warehousing-publisher-app

description: This API will allow the consumer to XXXX
version: v1
protocols: [HTTPS]
baseUri: https://int-p-warehousing-publisher-app/api/publisher-app/v1/publisher
mediaType: application/json

/publisher:
   get:

/dummy:
  get:    
      